import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';

class ContentSharingUtils {
  static Future<void> shareText({
    required String title,
    required String content,
    String? subject,
  }) async {
    await Share.share(
      '$title\n\n$content',
      subject: subject ?? title,
    );
  }

  static Future<void> shareFile({
    required String filePath,
    required String title,
    String? text,
  }) async {
    await Share.shareXFiles(
      [XFile(filePath)],
      text: text ?? title,
      subject: title,
    );
  }

  static Future<void> copyToClipboard(String text) async {
    await Clipboard.setData(ClipboardData(text: text));
  }

  static Future<void> shareContentWithFile({
    required String title,
    required String content,
    required String filePath,
  }) async {
    await Share.shareXFiles(
      [XFile(filePath)],
      text: '$title\n\n$content',
      subject: title,
    );
  }

  static Future<String> createShareableText({
    required String title,
    required String content,
    Map<String, dynamic>? metadata,
  }) async {
    String shareText = '$title\n\n$content';

    if (metadata != null) {
      shareText += '\n\n--- Details ---';

      if (metadata['subject'] != null) {
        shareText += '\nSubject: ${metadata['subject']}';
      }

      if (metadata['gradeLevel'] != null) {
        shareText += '\nGrade Level: ${metadata['gradeLevel']}';
      }

      if (metadata['language'] != null) {
        shareText += '\nLanguage: ${metadata['language']}';
      }

      shareText += '\n\nGenerated by AI Teaching Assistant';
    }

    return shareText;
  }
}
